KeyError in file /home/cstansbu/git_repositories/pip-fucci/Snakefile, line 18:
'filePath'
  File "/home/cstansbu/git_repositories/pip-fucci/Snakefile", line 18, in <module>
  File "/home/cstansbu/git_repositories/pip-fucci/utils/utils.py", line 47, in expandImageIds
  File "/home/cstansbu/miniconda3/envs/pf/lib/python3.11/site-packages/pandas/core/series.py", line 981, in __getitem__
  File "/home/cstansbu/miniconda3/envs/pf/lib/python3.11/site-packages/pandas/core/series.py", line 1089, in _get_value
  File "/home/cstansbu/miniconda3/envs/pf/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
